"""Launches installed Chrome/Edge/Brave/Chromium with isolated profiles.

Security rules enforced here (unlike the audited third-party app):
  - NO --remote-debugging-port, NO --remote-allow-origins (nothing can drive
    your logged-in tabs from outside the app).
  - No silent flags downloaded from anywhere; every flag is in this file.
  - Proxy credentials go through a tiny per-profile auth extension that only
    answers auth challenges (source generated below, fully inspectable).
"""
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

from .profiles import resource_path
from .proxy_tools import format_for_chrome
from .relay import ProxyRelay
from .user_agents import get_preset

RUNNING: dict[str, subprocess.Popen] = {}
RELAYS: dict[str, ProxyRelay] = {}  # profile_id -> local auth relay

PROXY_AUTH_MANIFEST = """{
  "manifest_version": 3,
  "name": "SafeProfiles Proxy Auth",
  "version": "1.0.0",
  "description": "Supplies proxy credentials for this profile only.",
  "permissions": ["webRequest", "webRequestAuthProvider"],
  "host_permissions": ["<all_urls>"],
  "background": {"service_worker": "bg.js"}
}
"""

PROXY_AUTH_BG = """// Auto-generated by SafeProfiles for ONE profile. Supplies that profile's
// proxy username/password to auth challenges. Nothing else.
const CREDS = __CREDS__;
chrome.webRequest.onAuthRequired.addListener(
  (details) => {
    if (details.isProxy === true) {
      return { authCredentials: { username: CREDS.u, password: CREDS.p } };
    }
  },
  { urls: ["<all_urls>"] },
  ["blocking"]
);
"""


def find_browsers() -> list:
    """Detect installed Chromium-based browsers. Returns [{name, path}]."""
    found: list = []
    seen: set[str] = set()

    def add(name: str, path: str | Path | None):
        if not path:
            return
        p = str(path)
        if p and os.path.isfile(p) and p not in seen:
            seen.add(p)
            found.append({"name": name, "path": p})

    if sys.platform == "win32":
        pf = os.environ.get("ProgramFiles", r"C:\Program Files")
        pfx = os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)")
        lad = os.environ.get("LOCALAPPDATA", "")
        add("Chrome", os.path.join(pf, "Google", "Chrome", "Application", "chrome.exe"))
        add("Chrome", os.path.join(pfx, "Google", "Chrome", "Application", "chrome.exe"))
        add("Chrome", os.path.join(lad, "Google", "Chrome", "Application", "chrome.exe"))
        add("Edge", os.path.join(pf, "Microsoft", "Edge", "Application", "msedge.exe"))
        add("Edge", os.path.join(pfx, "Microsoft", "Edge", "Application", "msedge.exe"))
        add("Brave", os.path.join(pf, "BraveSoftware", "Brave-Browser", "Application", "brave.exe"))
        add("Brave", os.path.join(pfx, "BraveSoftware", "Brave-Browser", "Application", "brave.exe"))
        add("Chromium (Playwright)", os.path.join(lad, "ms-playwright", "chromium-1234", "chrome-win64", "chrome.exe"))
        # any other playwright chromium build
        pw = Path(lad) / "ms-playwright" if lad else None
        if pw and pw.is_dir():
            for child in pw.glob("chromium-*/chrome-win*/chrome.exe"):
                add("Chromium (Playwright)", child)
    else:
        for name, binary in (("Chrome", "google-chrome"), ("Chromium", "chromium"),
                             ("Chromium", "chromium-browser"), ("Edge", "microsoft-edge"),
                             ("Brave", "brave-browser")):
            add(name, shutil.which(binary))
    return found


def resolve_browser(choice: str) -> dict | None:
    browsers = find_browsers()
    if not browsers:
        return None
    if not choice or choice == "auto":
        return browsers[0]
    for b in browsers:
        if b["path"] == choice or b["name"] == choice:
            return b
    return browsers[0]


def _write_proxy_auth_ext(profile_dir: Path, username: str, password: str) -> Path:
    ext = profile_dir / "proxy_auth_ext"
    ext.mkdir(exist_ok=True)
    (ext / "manifest.json").write_text(PROXY_AUTH_MANIFEST, encoding="utf-8")
    creds = json.dumps({"u": username, "p": password})
    (ext / "bg.js").write_text(PROXY_AUTH_BG.replace("__CREDS__", creds), encoding="utf-8")
    return ext


def _ensure_gh_relay(profile: dict, store) -> ProxyRelay:
    """Relay for a GitHub tunnel: follows the CURRENT tunnel address (it
    rotates ~hourly) and keeps a stable per-profile port so an open browser
    window survives both address rotations and app restarts."""
    pid = profile["id"]
    gh_id = profile.get("ghAccountId", "")
    key = ("github", gh_id)
    acc = store.gh.get(gh_id)  # KeyError handled by caller
    relay = RELAYS.get(pid)
    if relay is not None and getattr(relay, "key", None) == key and relay.port:
        return relay
    if relay is not None:
        relay.stop()

    def resolver():
        a = store.gh.get(gh_id)
        ep = a.get("endpoint") or ""
        if ":" not in ep:
            raise ConnectionError("tunnel endpoint not ready yet")
        return ep.rsplit(":", 1)

    relay = ProxyRelay("socks5", "", 0, acc.get("socksUser", ""),
                       store.gh.socks_password_by_id(gh_id),
                       resolver=resolver,
                       preferred_port=int(profile.get("relayPort") or 0)).start()
    relay.key = key  # type: ignore[attr-defined]
    RELAYS[pid] = relay
    # remember the port so the next launch (even after an app restart)
    # recreates the relay exactly where the browser expects it
    if store.get(pid) is not None:
        store.get(pid)["relayPort"] = relay.port
        store.save()
    return relay


def _ensure_relay(profile_id: str, proxy: dict) -> ProxyRelay:
    """Local SOCKS5 relay carrying this profile's proxy credentials."""
    key = ((proxy.get("protocol") or "http").lower(), proxy.get("host", ""),
           int(proxy.get("port") or 0), proxy.get("username", ""), proxy.get("password", ""))
    relay = RELAYS.get(profile_id)
    if relay is not None and getattr(relay, "key", None) == key and relay.port:
        return relay
    if relay is not None:
        relay.stop()
    relay = ProxyRelay(*key).start()
    relay.key = key  # type: ignore[attr-defined]
    RELAYS[profile_id] = relay
    return relay


def _write_fingerprint_ext(profile_dir: Path, profile: dict, preset: dict) -> Path | None:
    """Copy the fingerprint extension template and bake in this profile's seed."""
    template = resource_path("extension")
    if not (template / "manifest.json").exists():
        return None
    ext = profile_dir / "fingerprint_ext"
    if ext.exists():
        shutil.rmtree(ext, ignore_errors=True)
    shutil.copytree(template, ext)
    config = {
        "seed": profile.get("seed", "default"),
        "isMobile": bool(profile.get("isMobile", preset.get("isMobile"))),
        "cores": preset.get("cores", 8),
        "memory": preset.get("memory", 8),
        "gpuVendor": preset.get("gpuVendor", ""),
        "gpuRenderer": preset.get("gpuRenderer", ""),
        "screen": preset.get("screen", {}),
        "platform": preset.get("platform", ""),
        "timezone": profile.get("timezone", "") or None,
        "userAgent": profile.get("userAgent", ""),
    }
    (ext / "profile-config.js").write_text(
        "window.__SP_CONFIG__ = " + json.dumps(config) + ";", encoding="utf-8")
    return ext


def _verify_tunnel(profile: dict, store, relay: ProxyRelay) -> None:
    """Fail FAST with a clear message if the tunnel is dead, instead of
    launching a browser that later shows 'no network'."""
    from .proxy_tools import test_proxy
    for attempt in (1, 2):
        res = test_proxy("socks5", "127.0.0.1", relay.port, "", "", timeout=12)
        if res.get("success"):
            print(f"[tunnel] {profile.get('name', profile['id'])}: exit IP "
                  f"{res.get('ip')} ({res.get('country')})", flush=True)
            return
        if attempt == 1:
            time.sleep(5)  # maybe mid-rotation; let the poller catch up
    reason = res.get("error", "unknown error")
    raise RuntimeError(
        "This profile's tunnel is NOT working (dead address or the tunnel's "
        "GitHub account was banned). Open the Proxies tab: if the account "
        "shows 'dead', Remove it and add a NEW GitHub account, then Edit "
        "profile -> pick the new tunnel. If it was rotating, wait a minute "
        "and Launch again. (Reason: " + str(reason) + ")")


def build_command(profile: dict, data_dir: Path, store) -> tuple[list, str]:
    """Returns (argv, profile_dir). Raises RuntimeError if no browser found."""
    browser = resolve_browser(profile.get("browser", "auto"))
    if not browser:
        raise RuntimeError("No Chrome/Edge/Brave/Chromium found. Install Google Chrome and try again.")
    preset = get_preset(profile.get("uaPreset", "win_chrome"))

    profile_dir = Path(data_dir) / "browsers" / profile["id"]
    profile_dir.mkdir(parents=True, exist_ok=True)

    ua = profile.get("userAgent") or preset["userAgent"]
    vp = profile.get("viewport") or preset["viewport"]
    locale = (profile.get("locale") or "en-US").replace("_", "-")

    extensions: list[str] = []
    fp_ext = _write_fingerprint_ext(profile_dir, profile, preset)
    if fp_ext:
        extensions.append(str(fp_ext))

    proxy_args: list[str] = []
    proxy_needs_auth_ext = False
    mode = profile.get("proxyMode", "none")
    proxy: dict = {}
    if mode == "custom":
        proxy = dict(profile.get("customProxy") or {})
        proxy["password"] = store.proxy_password(profile)
    elif mode == "pool":
        proxy = dict(profile.get("poolProxy") or {})
    elif mode == "github":
        gh = getattr(store, "gh", None)
        try:
            acc = gh.get(profile.get("ghAccountId", "")) if gh else None
        except KeyError:
            acc = None
        if not acc:
            raise RuntimeError("No GitHub tunnel account selected. "
                               "Edit profile -> Proxy -> GitHub tunnel.")
        if not acc.get("endpoint") or ":" not in str(acc.get("endpoint")):
            raise RuntimeError("Tunnel not ready yet. Proxies tab -> GitHub Tunnels: "
                               "press Start, wait 1-2 minutes, then Refresh.")
        gh_host, gh_port = str(acc["endpoint"]).rsplit(":", 1)
        proxy = {"protocol": "socks5", "host": gh_host, "port": gh_port,
                 "username": acc.get("socksUser", ""),
                 "password": gh.socks_password_by_id(acc["id"])}
    if proxy.get("host") and proxy.get("port"):
        if proxy.get("username"):
            # Chrome 137+ (branded) ignores --load-extension, so the old
            # auth-extension trick is unreliable. Route through a local
            # no-auth SOCKS5 relay that applies the credentials itself.
            try:
                if mode == "github":
                    relay = _ensure_gh_relay(profile, store)
                    proxy_args.append(f"--proxy-server=socks5://127.0.0.1:{relay.port}")
                    _verify_tunnel(profile, store, relay)
                else:
                    relay = _ensure_relay(profile["id"], proxy)
                    proxy_args.append(f"--proxy-server=socks5://127.0.0.1:{relay.port}")
            except OSError:
                # Fallback for older/other browsers: per-profile auth extension.
                proxy_args.append(f"--proxy-server={format_for_chrome(proxy)}")
                auth_ext = _write_proxy_auth_ext(profile_dir, proxy["username"], proxy.get("password", ""))
                extensions.append(str(auth_ext))
                proxy_needs_auth_ext = True
        else:
            proxy_args.append(f"--proxy-server={format_for_chrome(proxy)}")
        proxy_args.append("--disable-quic")  # never let UDP leak around the proxy

    cmd = [
        browser["path"],
        f"--user-data-dir={profile_dir}",
        "--profile-directory=Default",
        "--no-first-run",
        "--no-default-browser-check",
        f"--user-agent={ua}",
        f"--window-size={vp.get('width', 1280)},{vp.get('height', 800)}",
        f"--lang={locale}",
        # Privacy / anti-fingerprint-leak flags (NOT remote control):
        "--disable-blink-features=AutomationControlled",
        "--force-webrtc-ip-handling-policy=disable_non_proxied_udp",
        "--enforce-webrtc-ip-permission-check",
        "--disable-features=TranslateUI",
        "--password-store=basic",
        "--test-type",
    ]
    if extensions:
        joined = ",".join(extensions)
        cmd.append(f"--load-extension={joined}")
        cmd.append(f"--disable-extensions-except={joined}")
    cmd.extend(proxy_args)
    if profile.get("isMobile"):
        cmd.append("--touch-events=enabled")
    start_url = profile.get("startUrl") or "about:blank"
    cmd.append(start_url)
    note = ("proxy-auth-extension" if proxy_needs_auth_ext else "no-proxy-auth")
    return cmd, str(profile_dir)


def launch(profile: dict, data_dir: Path, store) -> int:
    """Launch the browser for a profile. Returns PID."""
    existing = RUNNING.get(profile["id"])
    if existing and existing.poll() is None:
        return existing.pid
    cmd, _ = build_command(profile, data_dir, store)
    creationflags = 0
    if sys.platform == "win32":
        creationflags = getattr(subprocess, "CREATE_NO_WINDOW", 0)
    proc = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                            stdin=subprocess.DEVNULL, creationflags=creationflags)
    RUNNING[profile["id"]] = proc
    return proc.pid


def stop(profile_id: str) -> bool:
    relay = RELAYS.pop(profile_id, None)
    if relay is not None:
        relay.stop()
    proc = RUNNING.get(profile_id)
    if not proc:
        return False
    try:
        proc.terminate()
        try:
            proc.wait(timeout=8)
        except subprocess.TimeoutExpired:
            proc.kill()
    except OSError:
        pass
    RUNNING.pop(profile_id, None)
    return True


def is_running(profile_id: str) -> bool:
    proc = RUNNING.get(profile_id)
    if not proc:
        return False
    if proc.poll() is None:
        return True
    RUNNING.pop(profile_id, None)
    relay = RELAYS.pop(profile_id, None)
    if relay is not None:
        relay.stop()
    return False


def running_pids() -> dict:
    out = {}
    for pid in list(RUNNING):
        if is_running(pid):
            out[pid] = RUNNING[pid].pid
    return out
